const carsData = [
    { 
        title: "Ferrari F40", 
        category: "supercars", 
        badgeCato: "Supercars",
        cardImg: "../Graphics/Page7/Ferrari-F40.jpg", 
        modalImg: "../Graphics/Page7/Ferrari-F40-LBWK.jpg",
        alt: "Ferrari F40 Car",
        manufacturer: "Ferrari", 
        country: "Italy", 
        engine: "2.9L Twin-Turbo V8", 
        power: "~471 hp", 
        fact: "The F40 was the last car personally approved by Enzo Ferrari.", 
        link: "https://www.ferrari.com/en-SG" 
    },
    { 
        title: "McLaren P1", 
        category: "supercars", 
        badgeCato: "Supercars",
        cardImg: "../Graphics/Page7/Mclaren-P1.jpg", 
        modalImg: "../Graphics/Page7/MADMAC-P1.jpg",
        alt: "Mclaren P1",
        manufacturer: "McLaren", 
        country: "United Kingdom", 
        engine: "Twin-Turbo V8 Hybrid", 
        power: "~903 hp combined", 
        fact: "The P1 was designed with Formula One-derived hybrid technology.", 
        link: "https://www.mclaren.com/cars/gl_en" 
    },
    {
        title: "Lamborghini Aventador",
        category: "supercars",
        badgeCato: "Supercars",
        cardImg: "../Graphics/Page7/Lamborghini-aventador-FrontQuarter.jpg",
        modalImg: "../Graphics/Page7/Lamborghini-aventador-LBWK.jpg",
        alt: "Lamborghini Aventador",
        manufacturer: "Lamborghini",
        country: "Italy",
        engine: "6.5L Naturally Aspirated V12",
        power: "~700 hp",
        fact: "The Aventador's naturally aspirated V12 is among the last of its kind.",
        link: "https://https://www.lamborghini.com/en-en"
    },
    {
        title: "Porsche 911",
        category: "sports",
        badgeCato: "Sports Cars",
        cardImg: "../Graphics/Page7/Porsche-911-992Turbo.jpg",
        modalImg: "../Graphics/Page7/Porsche-911-Indecent.jpg",
        alt: "Porsche 911 992",
        manufacturer: "Porsche",
        country: "Germany",
        engine: "Flat-Six",
        layout: "Rear-Engine",
        fact: "Initially launched as the 901, but changed it to 911 as Peugeot owned the trademark to all three-digit car names with a zero in the middle.",
        link: "https://www.porsche.com/singapore/"
    },
    {
        title: "Toyota GR Supra",
        category: "sports",
        badgeCato: "Sports Cars",
        cardImg: "../Graphics/Page7/Toyota-Supra.jpg",
        modalImg: "../Graphics/Page7/Toyota-Supra-LBWK.jpg",
        alt: "Toyota GR Supra",
        manufacturer: "Toyota",
        country: "Japan",
        engine: "3.0L Turbo Inline-Six",
        power: " ~382 hp",
        fact: "The fifth-generation Supra was co-developed with BMW.",
        link: "https://www.toyota.com.sg"
    },
    {
        title: "Nissan Fairlady Z",
        category: "sports",
        badgeCato: "Sports Cars",
        cardImg: "../Graphics/Page7/Nissan-Fairlady-Z.jpg",
        modalImg: "../Graphics/Page7/Nissan-Fairlady-Z-LBWK.jpg",
        alt: "Nissan Fairlady Z",
        manufacturer: "Nissan",
        country: "Japan",
        engine: "3.0L Twin-Turbo V6",
        power: "~400 hp",
        fact: "The Z nameplate traces its roots back to the 1969 Fairlady Z.",
        link: "https://www.nissan.com.sg"
    },
    {
        title: "Nissan GTR",
        category: "JDM",
        badgeCato: "JDM",
        cardImg: "../Graphics/Page7/Nissan-GTR-R35T.jpg",
        modalImg: "../Graphics/Page7/Nissan-GTR-R35-LBWK.jpg",
        alt: "Nissan GTR R35",
        manufacturer: "Nissan",
        country: "Japan",
        engine: "3.8L Twin-Turbo V6",
        drivetrain: "AWD",
        fact: "Nicknamed 'Godzilla' for its dominance on the track.",
        link: "https://www.nissan.com.sg"
    },
    {
        title: "Toyota AE86",
        category: "JDM",
        badgeCato: "JDM",
        cardImg: "../Graphics/Page7/Toyota-AE86.jpg",
        modalImg: "../Graphics/Page7/Toyota-AE86-Tofu.jpg",
        alt: "Toyota AE86 JDM",
        manufacturer: "Nissan",
        country: "Japan",
        engine: "1.6L Naturally Aspirated",
        drivetrain: "RWD",
        fact: "Popularised worldwide through motorsport and drift culture.",
        link: "https://www.toyota.com.sg"
    },
    {
        title: "Honda NSX",
        category: "JDM",
        badgeCato: "JDM",
        cardImg: "../Graphics/Page7/Honda-NSX-1Gen.jpg",
        modalImg: "../Graphics/Page7/Honda-NSX-LBWK.jpg",
        alt: "Honda NSX JDM",
        manufacturer: "Honda",
        country: "Japan",
        engine: "3.0L / 3.2L Naturally Aspirated V6",
        drivetrain: "RWD",
        fact: "Developed with input from Formula One driver Ayrton Senna",
        link: "https://www.honda.com.sg"
    },
    {
        title: "Porsche Taycan",
        category: "electric",
        badgeCato: "Electric",
        cardImg: "../Graphics/Page7/Porsche-Taycan-GTS.jpg",
        modalImg: "../Graphics/Page7/Porsche-Taycan-GT-Manthey.jpg",
        alt: "Porsche Taycan",
        manufacturer: "Porsche",
        country: "Germany",
        powertrain: "Dual Electric Motors",
        drivetrain: "AWD",
        fact: "Porsche's first purpose-built electric vehicle.",
        link: "https://www.porsche.com/singapore/"
    },
    {
        title: "Tesla Model S Plaid",
        category: "electric",
        badgeCato: "Electric",
        cardImg: "../Graphics/Page7/Tesla-Model-S-Plaid.jpg",
        modalImg: "../Graphics/Page7/Tesla-Model-S-Plaid-Widebody.jpg",
        alt: "Tesla Model S Plaid",
        manufacturer: "Tesla",
        country: "United States",
        powertrain: "Tri-Motor Electric",
        zerotohun: "Under 2.1s",
        fact: "One of the fastest-accelerating production cars ever built.",
        link: "https://www.tesla.com/en_sg" 
    },
    {
        title: "Hyundai IONIQ 5 N",
        category: "electric",
        badgeCato: "Electric",
        cardImg: "../Graphics/Page7/Hyundai-Ioniq5-N.jpg",
        modalImg: "../Graphics/Page7/Hyundai-Ioniq-5-DK.jpg",
        alt: "Hyundai IONIQ 5 N",
        manufacturer: "Hyundai",
        country: "South Korea",
        powertrain: "Dual Electric Motors",
        power: "~641 hp",
        fact: "Simulates gear shifts and engine sound to mimic a petrol performance car.",
        link: "https://hyundai.com.sg"
    },
    {
        title: "Ferrari 499P",
        category: "motorsport",
        badgeCato: "Motorsport",
        cardImg: "../Graphics/Page7/Ferrari-499P.jpg",
        modalImg: "../Graphics/Page7/Ferrari-499P-HY.jpg",
        alt: "Ferrari 499P Hypercar",
        manufacturer: "Ferrari",
        carCato: "Hypercar (WEC)",
        powertrain: "Hybrid V6",
        series: "World Endurance Championship (WEC)",
        fact: "Returned Ferrari to overall victory at Le Mans after 60 years away.",
        link: "https://www.ferrari.com/en-EN/hypercar"
    },
    {
        title: "Porsche 963",
        category: "motorsport",
        badgeCato: "Motorsport",
        cardImg: "../Graphics/Page7/Porsche-963.jpg",
        modalImg: "../Graphics/Page7/Porsche-963-HY.jpg",
        alt: "Porsche 963 Hypercar",
        manufacturer: "Porsche",
        carCato: "GTP (IMSA)",
        powertrain: "Hybrid V8",
        series: "IMSA",
        fact: "Marked Porsche's return to top-class endurance prototype racing.",
        link: "https://racing.porsche.com/en-SG/cars/porsche-963"
    },
    {
        title: "Toyota GR010",
        category: "motorsport",
        badgeCato: "Motorsport",
        cardImg: "../Graphics/Page7/Toyota-GR010.jpg",
        modalImg: "../Graphics/Page7/Toyota-GR010-HY.jpg",
        alt: "Toyota GR010 Hypercar",
        manufacturer: "Toyota",
        carCato: "Hypercar (WEC)",
        powertrain: "Hybrid V6",
        series: "World Endurance Championship (WEC)",
        fact: "Toyota's hybrid hypercar has claimed back-to-back Le Mans victories.",
        link: "https://toyota-racing.com/toyota-racing-wec/"
    }
];